add linting for base-href
allaboutapps/cra-template-aaa-typescript pull request #26
Opened 2023-01-12 15:44 UTC by sretenovicstefan

2023-01-13 08:15 UTC, gottfired requested changes

2023-01-13 08:15 UTC, gottfired commented on template/scripts/lint-base-href.sh
> +baseCount="$(grep -rw --exclude-dir="node_modules" --include=\*.{html,htm} -e "<base href=\"\/\">" | wc -l)"
Ich würd die Regex erweitern auf `<base href=("\/"|'\/')>` damit auch `<base href='/'>`gematcht wird.

2023-01-16 09:24 UTC, sretenovicstefan commented on template/scripts/lint-base-href.sh
> +baseCount="$(grep -rw --exclude-dir="node_modules" --include=\*.{html,htm} -e "<base href=\"\/\">" | wc -l)"
c687f26549f4e4fcb06e87df754492bf08bf8a98

2023-01-19 08:07 UTC, gottfired approved these changes

2023-02-03 13:03 UTC, merged